name: Deployment of Pull Request Artifacts to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches:
      - 'main'
jobs:
  Deploy-Pull-Request:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: vercel_deploy
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment_output.txt

      - name: Output Vercel Deployment Details
        run: |
          echo 'Deployment output:'
          cat deployment_output.txt
          echo ''
          DEPLOY_URL=$(grep -Eo 'https://[a-zA-Z0-9.-]+\.vercel\.app' deployment_output.txt | head -n 1)
          echo "::notice title=Vercel Deployment URL::$DEPLOY_URL"
          echo "Deployed URL: $DEPLOY_URL"
