name: Deployment to Production (Manual)

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: string

jobs:
  publish-planit-api:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout tag
        run: git checkout ${{ github.event.inputs.tag }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Apply Terraform Configuration
        run: |
          cd ./apps/planit-iac
          terraform init
          terraform apply -auto-approve

  publish-planit-web:
    runs-on: ubuntu-latest
    needs: publish-planit-api
    environment: production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout tag
        run: git checkout ${{ github.event.inputs.tag }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
